import type { PluginHostProps } from "@getpaseo/plugin/client";
import { useMemo } from "react";
import { StyleSheet } from "react-native";

export function useStyles({ theme, layout }: Pick<PluginHostProps, "theme" | "layout">) {
  return useMemo(() => {
    const c = theme.colors;
    const pad = layout.compact ? 12 : 20;
    return StyleSheet.create({
      screen: { flex: 1, backgroundColor: c.surface0 },
      header: {
        paddingHorizontal: pad,
        paddingTop: pad,
        paddingBottom: 8,
        gap: 10,
      },
      headerRow: { flexDirection: "row", alignItems: "center", gap: 10 },
      title: { color: c.foreground, fontSize: layout.compact ? 20 : 22, fontWeight: "600", flex: 1 },
      muted: { color: c.foregroundMuted, fontSize: 13 },
      small: { color: c.foregroundMuted, fontSize: 12 },
      text: { color: c.foreground, fontSize: 14, lineHeight: 20 },
      danger: { color: c.statusDanger, fontSize: 13 },
      iconButton: {
        padding: 8,
        borderRadius: 8,
        borderWidth: StyleSheet.hairlineWidth,
        borderColor: c.border,
        backgroundColor: c.surface1,
      },
      chips: { gap: 8, paddingRight: pad },
      chip: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 999,
        borderWidth: StyleSheet.hairlineWidth,
        borderColor: c.border,
        backgroundColor: c.surface1,
      },
      chipActive: { backgroundColor: c.accent, borderColor: c.accent },
      chipText: { color: c.foreground, fontSize: 13 },
      chipTextActive: { color: c.accentForeground, fontSize: 13, fontWeight: "600" },
      input: {
        color: c.foreground,
        backgroundColor: c.surface1,
        borderColor: c.border,
        borderWidth: StyleSheet.hairlineWidth,
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 8,
        fontSize: 14,
      },
      body: { flex: 1, flexDirection: "row" },
      board: { flex: 1 },
      columns: { flex: 1, flexDirection: "row", gap: 12, paddingHorizontal: pad, paddingBottom: pad },
      column: {
        flex: 1,
        minWidth: 220,
        backgroundColor: c.surface1,
        borderRadius: 10,
        borderWidth: StyleSheet.hairlineWidth,
        borderColor: c.border,
      },
      columnHeader: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        paddingHorizontal: 12,
        paddingVertical: 10,
      },
      columnTitle: { color: c.foreground, fontSize: 13, fontWeight: "600", flex: 1 },
      columnBody: { paddingHorizontal: 8, paddingBottom: 8, gap: 8 },
      stacked: { paddingHorizontal: pad, paddingBottom: pad, gap: 16 },
      section: { gap: 8 },
      card: {
        padding: 12,
        gap: 6,
        borderRadius: 8,
        borderWidth: StyleSheet.hairlineWidth,
        borderColor: c.border,
        backgroundColor: c.surface2,
      },
      cardSelected: { borderColor: c.accent, borderWidth: 2 },
      cardRow: { flexDirection: "row", alignItems: "center", gap: 6, flexWrap: "wrap" },
      key: { color: c.foregroundMuted, fontSize: 12, fontWeight: "600", fontFamily: "monospace" },
      summary: { color: c.foreground, fontSize: 14, lineHeight: 19 },
      pill: {
        paddingHorizontal: 8,
        paddingVertical: 2,
        borderRadius: 999,
        borderWidth: 1,
      },
      pillText: { fontSize: 11, fontWeight: "600" },
      dot: { width: 8, height: 8, borderRadius: 4 },
      centered: { flex: 1, alignItems: "center", justifyContent: "center", padding: pad, gap: 12 },
      detail: {
        backgroundColor: c.surface0,
        borderLeftWidth: layout.compact ? 0 : StyleSheet.hairlineWidth,
        borderColor: c.border,
      },
      detailWide: { width: "42%", minWidth: 320 },
      detailBody: { padding: pad, gap: 14 },
      detailTitle: { color: c.foreground, fontSize: 18, fontWeight: "600", lineHeight: 24 },
      fieldGrid: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
      field: { minWidth: 120, gap: 2 },
      sectionTitle: { color: c.foreground, fontSize: 14, fontWeight: "600" },
      comment: {
        gap: 4,
        padding: 10,
        borderRadius: 8,
        backgroundColor: c.surface1,
        borderWidth: StyleSheet.hairlineWidth,
        borderColor: c.border,
      },
      button: {
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 8,
        backgroundColor: c.accent,
      },
      buttonText: { color: c.accentForeground, fontSize: 13, fontWeight: "600" },
      secondaryButton: {
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 8,
        borderWidth: StyleSheet.hairlineWidth,
        borderColor: c.border,
        backgroundColor: c.surface1,
      },
      secondaryButtonText: { color: c.foreground, fontSize: 13 },
    });
  }, [theme, layout.compact]);
}

export type Styles = ReturnType<typeof useStyles>;
